Update backup

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Check if the script is running as root
+if [[ $EUID -ne 0 ]]; then
+   echo "This script must be run as root."
+   exit 1
+fi
+
 echo "Starting system cleanup..."
 sudo apt clean
 sudo apt autoremove -y
@@ -18,20 +24,32 @@ fi
 # Create the backup directory if it does not exist
 mkdir -p "$BACKUP_DIR"
 
-# Create the backup archive, specifically including ~/develop and ~/github
-tar -czf "$BACKUP_DIR/$BACKUP_FILE" --exclude="$BACKUP_DIR" "$HOME" "$HOME/develop" "$HOME/github"
+# Create the backup archive
+tar -czf "$BACKUP_DIR/$BACKUP_FILE" --exclude="$BACKUP_DIR" "$HOME"
 
-# Backup configuration files
-cp -u $HOME/.bashrc $HOME/.bashrc.bak
-cp -u $HOME/.bashrc $BACKUP_DIR
-cp -u $HOME/.bashrc.bak $BACKUP_DIR
-cp -u $HOME/.vimrc $BACKUP_DIR
-cp -u $HOME/.local/share/backgrounds/* "$BACKUP_DIR" 2>/dev/null
+echo "Starting backup of configuration files..."
 
-echo "Backup created in: $BACKUP_DIR"
+# Create an array of files to back up
+config_files=("$HOME/.bashrc" "$HOME/.vimrc" "$HOME/.local/share/backgrounds/*")
 
-# Copy files from local backup to external hard drive
-cp -u $BACKUP_DIR/* $BACKUP_DIR_EXT
+# Create a backup of .bashrc before modifying
+if [ -f "$HOME/.bashrc" ]; then
+    cp -u "$HOME/.bashrc" "$HOME/.bashrc.bak"
+fi
+
+# Loop through the array and copy each file to the backup directory
+for file in "${config_files[@]}"; do
+    if [ -f "$file" ] || [ -d "$file" ]; then
+        cp -ur $file "$BACKUP_DIR"
+    else
+        echo "Warning: $file not found and will not be backed up."
+    fi
+done
+
+echo "Backup of configuration files created in: $BACKUP_DIR"
+
+# Copy files from local backup to external hard drive using rsync
+rsync -avh --progress $BACKUP_DIR/ $BACKUP_DIR_EXT
 
 echo "Backup copied to external drive."
 
