updated

diff --git a/dispatch b/dispatch
--- a/dispatch
+++ b/dispatch
@@ -54,6 +54,17 @@ for file in "${!DIRS[@]}"; do
     fi
 done
 
-dconf load '/com/gexperts/Tilix/' < "$GITHUB_DIR/tilix.conf" || echo -e "${RED}Failed to load tilix.conf.${NC}"
+# Check if dbus-x11 is installed
+if ! dpkg -s dbus-x11 &> /dev/null; then
+    echo "Installing dbus-x11..."
+    sudo apt-get install dbus-x11
+fi
+
+# Load the configuration file for Tilix
+if dconf load '/com/gexperts/Tilix/' < "$GITHUB_DIR/tilix.conf"; then
+    echo "Tilix configuration loaded successfully."
+else
+    echo -e "${RED}Failed to load tilix.conf.${NC}"
+fi
 
 echo -e "${YELLOW}All files have been copied successfully.${NC}"
