added tilis.conf

diff --git a/dispatch b/dispatch
--- a/dispatch
+++ b/dispatch
@@ -37,4 +37,7 @@ for file in "${!DIRS[@]}"; do
         fi
     fi
 done
+
+dconf load '/com/gexperts/Tilix/' < "$GITHUB_DIR/tilix.conf" || echo -e "${RED}Failed to load tilix.conf.${NC}"
+
 echo -e "${YELLOW}All files have been copied successfully.${NC}"
