removed nerdfonts

diff --git a/gitupd b/gitupd
--- a/gitupd
+++ b/gitupd
@@ -42,8 +42,7 @@ echo -e "${YELLOW}Updating configfiles...${NC}"
 rsync -avh --progress "$BASHRC_DIR/.bashrc" "$GITHUB_DIR/dot.bashrc"             || echo -e "${RED}Failed to update .bashrc${NC}"
 rsync -avh --progress "$VIMRC_DIR/.vimrc" "$GITHUB_DIR/dot.vimrc"                || echo -e "${RED}Failed to update .vimrc${NC}"
 rsync -avh --progress "$SCCONF_DIR/sc.conf" "$GITHUB_DIR/sc.conf"                || echo -e "${RED}Failed to update sc.conf${NC}"
-rsync -avh --progress "$RCLUA_DIR/rc.lua" "$GITHUB_DIR/rc.lua"                   || echo -e "${RED}Failed to update rc.lua${NC}"
-rsync -avh --progress "$RCLUA_DIR/rc.lua.original" "$GITHUB_DIR/rc.lua.original" || echo -e "${RED}Failed to update rc.lua.original${NC}"
+rsync -avh --progress "$RCLUA_DIR/rc.lua" "$GITHUB_DIR/rc.lua"                   || echo -e "${RED}Failed to update rc.lua${NC}" rsync -avh --progress "$RCLUA_DIR/rc.lua.original" "$GITHUB_DIR/rc.lua.original" || echo -e "${RED}Failed to update rc.lua.original${NC}"
 rsync -avh --progress "$RCCONF_DIR/rc.conf" "$GITHUB_DIR/rc.conf"                || echo -e "${RED}Failed to update rc.conf${NC}"
 rsync -avh --progress "$PICOM_DIR/picom.conf" "$GITHUB_DIR/picom.conf"           || echo -e "${RED}Failed to update picom.conf${NC}"
 rsync -avh --progress "$NFCONF_DIR/config.conf" "$GITHUB_DIR/nf.conf"            || echo -e "${RED}Failed to update (neofetch) config.conf${NC}"
@@ -51,9 +50,6 @@ dconf dump '/com/gexperts/Tilix/' > "$GITHUB_DIR/tilix.conf"  || echo -e "${RED}
 
 # Awesome-WM background
 cp "$AWMBG_DIR/background.png" "$GITHUB_DIR/awmbg.png" || echo -e "${RED}Failed to update background.png${NC}"
-
-# Fonts
-cp -r "$FONTS_DIR" "$GITHUB_DIR/" || echo -e "${RED}Failes to update fonts${NC}"
 
 echo
 echo -e "${YELLOW}Updating scripts...${NC}"
