cp > rsync

diff --git a/gitupd b/gitupd
--- a/gitupd
+++ b/gitupd
@@ -37,15 +37,15 @@ fi
 echo -e "${YELLOW}Updating configfiles...${NC}"
 
 # define config files
-cp "$BASHRC_DIR/.bashrc" "$GITHUB_DIR/dot.bashrc"             || echo -e "${RED}Failed to update .bashrc${NC}"
-cp "$VIMRC_DIR/.vimrc" "$GITHUB_DIR/dot.vimrc"                || echo -e "${RED}Failed to update .vimrc${NC}"
-cp "$SCCONF_DIR/sc.conf" "$GITHUB_DIR/sc.conf"                || echo -e "${RED}Failed to update sc.conf${NC}"
-cp "$RCLUA_DIR/rc.lua" "$GITHUB_DIR/rc.lua"                   || echo -e "${RED}Failed to update rc.lua${NC}"
-cp "$RCLUA_DIR/rc.lua.original" "$GITHUB_DIR/rc.lua.original" || echo -e "${RED}Failed to update rc.lua.original${NC}"
-cp "$RCCONF_DIR/rc.conf" "$GITHUB_DIR/rc.conf"                || echo -e "${RED}Failed to update rc.conf${NC}"
-cp "$PICOM_DIR/picom.conf" "$GITHUB_DIR/picom.conf"           || echo -e "${RED}Failed to update picom.conf${NC}"
-cp "$NFCONF_DIR/config.conf" "$GITHUB_DIR/nf.conf"            || echo -e "${RED}Failed to update (neofetch) config.conf${NC}"
-dconf dump '/com/gexperts/Tilix/' > "$GITHUB_DIR/tilix.conf"     || echo -e "${RED}Failed to dump tilix.conf{$NC}"
+rsync -avh --progress "$BASHRC_DIR/.bashrc" "$GITHUB_DIR/dot.bashrc"             || echo -e "${RED}Failed to update .bashrc${NC}"
+rsync -avh --progress "$VIMRC_DIR/.vimrc" "$GITHUB_DIR/dot.vimrc"                || echo -e "${RED}Failed to update .vimrc${NC}"
+rsync -avh --progress "$SCCONF_DIR/sc.conf" "$GITHUB_DIR/sc.conf"                || echo -e "${RED}Failed to update sc.conf${NC}"
+rsync -avh --progress "$RCLUA_DIR/rc.lua" "$GITHUB_DIR/rc.lua"                   || echo -e "${RED}Failed to update rc.lua${NC}"
+rsync -avh --progress "$RCLUA_DIR/rc.lua.original" "$GITHUB_DIR/rc.lua.original" || echo -e "${RED}Failed to update rc.lua.original${NC}"
+rsync -avh --progress "$RCCONF_DIR/rc.conf" "$GITHUB_DIR/rc.conf"                || echo -e "${RED}Failed to update rc.conf${NC}"
+rsync -avh --progress "$PICOM_DIR/picom.conf" "$GITHUB_DIR/picom.conf"           || echo -e "${RED}Failed to update picom.conf${NC}"
+rsync -avh --progress "$NFCONF_DIR/config.conf" "$GITHUB_DIR/nf.conf"            || echo -e "${RED}Failed to update (neofetch) config.conf${NC}"
+dconf dump '/com/gexperts/Tilix/' > "$GITHUB_DIR/tilix.conf"  || echo -e "${RED}Failed to dump tilix.conf{$NC}"
 
 # Awesome-WM background
 cp "$AWMBG_DIR/background.png" "$GITHUB_DIR/awmbg.png" || echo -e "${RED}Failed to update background.png${NC}"
@@ -55,7 +55,7 @@ echo -e "${YELLOW}Updating scripts...${NC}"
 # Here, you should define a list of specific scripts to be copied.
 declare -a scripts=("backup" "gitupd" "snapcrash" "update" "dispatch" "startup" "bye")
 for script in "${scripts[@]}"; do
-    cp "/usr/local/bin/$script" "$GITHUB_DIR/$script" || echo -e "${RED}Failed to update $script${NC}"
+    rsync -avh --progress "/usr/local/bin/$script" "$GITHUB_DIR/$script" || echo -e "${RED}Failed to update $script${NC}"
 done
 
 echo -e "${GREEN}Update process completed.${NC}"
