Deleted

diff --git a/gitupd b/gitupd
--- a/gitupd
+++ b/gitupd
@@ -38,37 +38,25 @@ fi
 echo
 echo -e "${YELLOW}Updating configfiles...${NC}"
 
-# define config files
+# config files
 rsync -avh --progress "$BASHRC_DIR/.bashrc" "$GITHUB_DIR/dot.bashrc"             || echo -e "${RED}Failed to update .bashrc${NC}"
 rsync -avh --progress "$VIMRC_DIR/.vimrc" "$GITHUB_DIR/dot.vimrc"                || echo -e "${RED}Failed to update .vimrc${NC}"
 rsync -avh --progress "$SCCONF_DIR/sc.conf" "$GITHUB_DIR/sc.conf"                || echo -e "${RED}Failed to update sc.conf${NC}"
-rsync -avh --progress "$RCLUA_DIR/rc.lua" "$GITHUB_DIR/rc.lua"                   || echo -e "${RED}Failed to update rc.lua${NC}" rsync -avh --progress "$RCLUA_DIR/rc.lua.original" "$GITHUB_DIR/rc.lua.original" || echo -e "${RED}Failed to update rc.lua.original${NC}"
+rsync -avh --progress "$RCLUA_DIR/rc.lua" "$GITHUB_DIR/rc.lua"                   || echo -e "${RED}Failed to update rc.lua${NC}"
+rsync -avh --progress "$RCLUA_DIR/rc.lua.original" "$GITHUB_DIR/rc.lua.original" || echo -e "${RED}Failed to update rc.lua.original${NC}"
 rsync -avh --progress "$RCCONF_DIR/rc.conf" "$GITHUB_DIR/rc.conf"                || echo -e "${RED}Failed to update rc.conf${NC}"
 rsync -avh --progress "$PICOM_DIR/picom.conf" "$GITHUB_DIR/picom.conf"           || echo -e "${RED}Failed to update picom.conf${NC}"
-rsync -avh --progress "$NFCONF_DIR/config.conf" "$GITHUB_DIR/nf.conf"            || echo -e "${RED}Failed to update (neofetch) config.conf${NC}"
-dconf dump '/com/gexperts/Tilix/' > "$GITHUB_DIR/tilix.conf"  || echo -e "${RED}Failed to dump tilix.conf{$NC}"
+rsync -avh --progress "$NFCONF_DIR/config.conf" "$GITHUB_DIR/nf.conf"            || echo -e "${RED}Failed to update nf.conf${NC}"
+dconf dump '/com/gexperts/Tilix/' > "$GITHUB_DIR/tilix.conf"                     || echo -e "${RED}Failed to dump tilix.conf{$NC}"
 
 # Awesome-WM background
-rsync -avh --progress "$AWMBG_DIR/background.png" "$GITHUB_DIR/awmbg.png" || echo -e "${RED}Failed to update background.png${NC}"
+rsync -avh --progress "$AWMBG_DIR/background.png" "$GITHUB_DIR/awmbg.png"        || echo -e "${RED}Failed to update background.png${NC}"
 
 # Nerdfonts
-rsync -avh --progress "$FONT_DIR/nerdfonts" "$GITHUB_DIR/" || echo -e "${RED}Failed to update nerdfonts${NC}"
+rsync -avh --progress "$FONT_DIR/nerdfonts" "$GITHUB_DIR/"                       || echo -e "${RED}Failed to update nerdfonts${NC}"
 
 # Tilix schemes
-# Check if the target directory exists
-if [ ! -d "$GITHUB_DIR/schemes/tilix" ]; then
-    echo -e "${BLUE}$GITHUB_DIR/schemes/tilix ${RED}does not exist.${NC}"
-    echo -e "${YELLOW}Creating ${BLUE}$GITHUB_DIR/schemes/tilix${NC}"
-    mkdir -p "$GITHUB_DIR/schemes/tilix"
-fi
-
-# Sync the Tilix schemes
-echo -e "${YELLOW}Copying files from ${BLUE}$SCHEMES_TILIX_DIR ${YELLOW}to ${BLUE}$GITHUB_DIR/schemes/tilix${NC}"
-if rsync -avh --progress "$SCHEMES_TILIX_DIR" "$GITHUB_DIR/schemes/tilix/"; then
-    echo -e "${GREEN}Tilix schemes updated successfully.${NC}"
-else
-    echo -e "${RED}Failed to update Tilix schemes${NC}"
-fi
+rsync -avh --progress "$TILIX_DIR/schemes" "$GITHUB_DIR/tilix/"                  || echo -e "${RED}Failed to update tilix schemes${NC}"
 
 echo
 echo -e "${YELLOW}Updating scripts...${NC}"
@@ -76,7 +64,7 @@ echo -e "${YELLOW}Updating scripts...${NC}"
 # Here, you should define a list of specific scripts to be copied.
 declare -a scripts=("backup" "gitupd" "snapcrash" "update" "dispatch" "startup" "bye" "mountman")
 for script in "${scripts[@]}"; do
-    rsync -avh --progress "/usr/local/bin/$script" "$GITHUB_DIR/$script" || echo -e "${RED}Failed to update $script${NC}"
+    rsync -avh --progress "/usr/local/bin/$script" "$GITHUB_DIR/$script"         || echo -e "${RED}Failed to update $script${NC}"
 done
 
 echo
