added sc.conf request

diff --git a/snapcrash b/snapcrash
--- a/snapcrash
+++ b/snapcrash
@@ -14,7 +14,14 @@
 # Requires root : Yes
 
 # Load config file
-source $HOME/.config/sc.conf
+CONFIG_FILE="$HOME/.config/sc.conf"
+if [[ -f "$CONFIG_FILE" ]]; then
+    source "$CONFIG_FILE"
+else
+    echo -e "${RED}Error: Configuration file not found.${NC}"
+    echo -e "${RED}Please ensure the configuration file 'sc.conf' exists at $HOME/.config/${NC}"
+    exit 1
+fi
 
 echo
 echo -e "${YELLOW}Deleting all Snap Store processes...${NC}"
