updated

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -6,14 +6,13 @@
 # \__ \ || (_| | |  | |_| |_| | |_) |
 # |___/\__\__,_|_|   \__|\__,_| .__/ 
 #                             |_|  
-#
-# file information
-# name:         startup (script)
-# location:     /usr/local/bin
-# function:     Install specified applications and run the 'dispatch' script to dispatch files from GitHub repository
-#
-# !! file information könnte ausführlicher sein!
-#
+# Script        : startup
+# Author        : Jens Ochmann
+# Description   : Install specified applications and run the 'dispatch' script to dispatch files from GitHub repository
+# Location      : /usr/local/bin
+# Requires root : Yes
+# Usage         : Execute with './startup' to install specified applications and dispatch the GitHub repository
+
 # Colors
 RED='\033[0;31m'
 YELLOW='\033[1;33m'
@@ -32,16 +31,16 @@ applications=(
     "vim-fugitive"  # Vim-fugitive, a Git wrapper for VIM
     "vim-gitgutter" # Vim plugin which shows a git diff in the 'gutter' (sign column)
     "vim-syntastic" # Syntastic is a syntax checking plugin
-    "vim-tabular"   # Vim script for text filterung and alignment
+    "vim-tabular"   # Vim script for text filtering and alignment
     "micro"         # Text editor
     "cmatrix"       # Cmatrix, displays the Matrix falling characters animation
     "trash-cli"     # Command interface for the recycle bin
     "exa"           # Modern replacement for ls
     "awesome"       # Highly configurable window manager for X
-    "qutebrowser"   # Keyboard-driven, vim-like brwoser
-    "picom"         # Lightweight compsitor for X11
+    "qutebrowser"   # Keyboard-driven, vim-like browser
+    "picom"         # Lightweight compositor for X11
     "figlet"        # converts user input into ASCII banners
-    "git".          # !! Beschreibung
+    "git"           # Distributed version control system
 )
 
 # Installing applications using apt-get
@@ -49,22 +48,30 @@ for app in "${applications[@]}"; do
     if sudo apt-get install -y $app; then
         echo -e "${YELLOW}Installed $app successfully.${NC}"
     else
-        echo -e "${RED}Failed to install $app.${NC}"
+        echo -e "${RED}Failed to install $app. Check if the package exists or if there are network issues.${NC}"
     fi
 done
 
 echo -e "${YELLOW}All desired applications have been installed.${NC}"
 
-# !! cd $HOME
-# !! Git -clone https://github.com/ochi84/github.git
-# !! sudo cp $HOME/github/dispatch /usr/local/bin/
-# !! sudo chmod +x /usr/local/bin/dispatch
+# Get the GitHub repository
+echo -e "${YELLOW}Cloning the GitHub repository 'github'.${NC}"
+cd $HOME
+if git clone https://github.com/ochi84/github.git; then
+    if sudo cp $HOME/github/dispatch /usr/local/bin/ && sudo chmod +x /usr/local/bin/dispatch; then
+        echo -e "${YELLOW}Dispatch script successfully installed and made executable.${NC}"
+    else
+        echo -e "${RED}Failed to install and set execute permission on dispatch script.${NC}"
+    fi
+else
+    echo -e "${RED}Failed to clone GitHub repository. Check if the URL is correct or if there are network issues.${NC}"
+    exit 1
+fi
 
 echo -e "${YELLOW}Running the 'dispatch' script...${NC}"
 
 # Ensure that the 'dispatch' script is executable and available in PATH
 if /usr/local/bin/dispatch; then
-    # !! dispatch, (geht das so?)
     echo -e "${YELLOW}Dispatch script executed successfully.${NC}"
 else
     echo -e "${RED}Failed to execute the dispatch script.${NC}"
